### ISSUE TITLE
Linear_SVM wrong norm_term

### ISSUE THREAD

**Issue by RayXie29** [machinelearningmindset/TensorFlow-Course#30]
`norm_term = tf.divide(tf.reduce_sum(tf.multiply(tf.transpose(W),W)),2)`

should be <br />

`norm_term= tf.divide(tf.matmul(tf.transpose(W),W),2)`

**Comment by astorfi** [comment]
Would please create a pull request? Why are you removing the tf.reduce_sum?

**Comment by RayXie29** [comment]
Since the shape of W is Nx1. So I assume that tf.matmul( tf.transpose(W), W ) would be 1xN * Nx1, which the output will be 1x1. But I think it is better to add tf.reduce_sum. Already pull the request, thanks for the repo. It is very helpful.
