### ISSUE TITLE
Several typos 

### ISSUE THREAD

**Issue by yurenzhang** [machinelearningmindset/TensorFlow-Course#31]
[Convolutional Neural Networks using TensorFlow](https://github.com/machinelearningmindset/TensorFlow-Course/tree/master/docs/tutorials/3-neural_network/convolutiona_neural_network)

 "is the one proposed by the paper Understanding the difficulty of training deep feedforward neural networks and provided by the TensorFlow." is repeated twice .

"this layer operates like **and filly-connected** layer"

"In **The** outputs of different layers"

**Comment by astorfi** [comment]
THank you. Resolved.
